### ISSUE TITLE
Rolls from Character and Monster sheet - two bugs

### ISSUE THREAD

**Issue by Dillatr** [AnthonyMonette/TheWitcherTRPG#282]
Clicking a skill to roll requires an actor to be selected, whereas before it didnt need an actor to be selected
![image](https://user-images.githubusercontent.com/91529833/210329254-4376410a-1dae-4a3e-8a55-e2121acd64f0.png)

Also, criticals/fumbles in chat rolls no longer show the button to do the reroll
![image](https://user-images.githubusercontent.com/91529833/210329337-39d0e578-50d2-4593-8550-704c5349d9ad.png)

**Comment by Dillatr** [comment]
bugs appeared after version 0.95

**Comment by Dillatr** [comment]
fumble and crit automatic rolls work correctly for STATS but not skills
![image](https://user-images.githubusercontent.com/91529833/210330185-a3b17b0c-67fd-463f-81fd-c4ef6bde5bd2.png)

**Comment by MaxAlvin** [comment]
I have the same bug

**Comment by MaxAlvin** [comment]
and a weapon with the "improved armor piercing" property simply ignores it
![игнор брони](https://user-images.githubusercontent.com/122493199/211933196-f91d4255-3a09-4677-b307-25dbf4d75168.png)

**Comment by MaxAlvin** [comment]
some weapons stop works... and more other.
how do I roll back to the previous version?

**Comment by AnthonyMonette** [comment]
A fix has been pushed, could you both confirm if everythings good now?

**Comment by Dillatr** [comment]
Fumble and crit work correctly (however fumbles include the 1 from the initial d10 in the total check)
Had issues with damage not subtracting armor SP from character tokens, but works correctly for monster tokens (doesn't matter if weapon has armor piercing / improved armor piercing / no armor piercing)
![image](https://user-images.githubusercontent.com/91529833/215320808-b6e18940-dd1a-4ac0-98dd-f2cb33722bb2.png)

**Comment by Dillatr** [comment]
Tokens dont need to be selected to roll from a character sheet, however the error message still shows up

**Comment by Galonas** [comment]
> Fumble and crit work correctly (however fumbles include the 1 from the initial d10 in the total check) Had issues with damage not subtracting armor SP from character tokens, but works correctly for monster tokens (doesn't matter if weapon has armor piercing / improved armor piercing / no armor piercing) ![image](https://user-images.githubusercontent.com/91529833/215320808-b6e18940-dd1a-4ac0-98dd-f2cb33722bb2.png)

I have seen this issue, SOmeone is looking into it or is there already a fix for it?
Thank you

**Comment by Galonas** [comment]
Hello again, I found where the problem is :
In action.js you have
![image](https://user-images.githubusercontent.com/25280036/222533327-1b36c5b9-91e9-4d25-b38c-65a0e8d51f5a.png)
and in tab-inventory.html you have
![image](https://user-images.githubusercontent.com/25280036/222533839-53a6ee1d-272f-49b8-a991-16114372613b.png)
Please notice the typo in "equipped" in action.js and "equiped" in the html file.

What is the best to do? Modify action.js or tab-inventory.html?
Note that you have to do it for every items that can be equipped.
Also, I have tested it by changing in the action.js and it's working.

**Comment by Melkkart** [comment]
Tu corre

> > La pifia y el crítico funcionan correctamente (sin embargo, las pifias incluyen el 1 del d10 inicial en la comprobación total) Tuvo problemas con el daño que no restaba SP de armadura de las fichas de personaje, pero funciona correctamente para fichas de monstruo (no importa si el arma tiene perforación de armadura / mejorada perforación de armadura / sin perforación de armadura)![imagen](https://user-images.githubusercontent.com/91529833/215320808-b6e18940-dd1a-4ac0-98dd-f2cb33722bb2.png)
> 
> Tuve el mismo problema y encontré el problema. Hice una solicitud de inserción para la corrección, gracias

Thks, I Fix the problem :)

**Comment by pedroaugustobt** [comment]
Does anyone know if it's been fixed yet? It's still happening to me

**Comment by Melkkart** [comment]
Hello, they haven't uploaded it yet, but I'll give you the corrected file.
https://drive.google.com/file/d/1wFlDMeiI6d0MqgLzHr7AbDilPJwzF9TJ/view?usp=sharing
replace the file
route: C:\Users\YOUUSER\AppData\Local\FoundryVTT\Data\systems\TheWitcherTRPG\scripts

**Comment by pedroaugustobt** [comment]
Thanks, i was trying to find an answer but i couldn't, thanks again

Em seg., 20 de mar. de 2023 13:43, Melkkart ***@***.***>
escreveu:

**Comment by 1991Dmitriy** [comment]
![2023-05-06_16-55-20](https://user-images.githubusercontent.com/124423448/236617338-8b74ad6f-d90b-4006-86b7-b36023c1b49e.png)
SP is still not working. The video file but did not find where to copy it, the actions file.

**Comment by ortegamarcel** [comment]
If you want, you can try out [my "development" version](https://github.com/ortegamarcel/TheWitcherTRPG/wiki). I am (currently) more active and have time to fix such issues. 

This version fixed the problem with the armor not being applied and has some more features like [Improved Inventory](https://github.com/ortegamarcel/TheWitcherTRPG/wiki/Features#improved-inventory) and [Zoomable Images](https://github.com/ortegamarcel/TheWitcherTRPG/wiki/Features#zoomable-images). I also created pull requests here, but they are not merged (available) yet. That version is also compatible with the [Token Action HUD TheWitcherTRPG](https://github.com/ortegamarcel/fvtt-token-action-hud-TheWitcherTRPG).

**Comment by Durins-Cat** [comment]
I am having the "At least one actor must be selected" issue when trying to roll from a character sheet. Works fine if i have an actor selected but i'd like to figure out a way to have it work like normal. I tried installing ortegamarcel's fork and the action script file above, but neither solves the issue. (Foundry vs. 11 Stable - Build 315)
